### PR TITLE
UniLayer

### PR DESCRIPTION
**Pull request by benlolbenlol178**
…top of Uniswap.

That enables key
features for professional-level trading with its LAYER
utility token, focusing on automated swaps and
liquidity management, flash staking, charts and
analytics, live order books, and a lot more.

### CODE REVIEW

**Comment by benlolbenlol178** [comment]
What is this? Please check.

**Review by ghost — APPROVED** [review]
Fee paid, review added.

**Comment by benlolbenlol178** [comment]
I have paid 1 BNB
https://explorer.binance.org/tx/2B9A53CFC79669053A460CD8BE019EE162CF416A1307742B32765BFD6111F585

**Comment by benlolbenlol178** [comment]
Is this ok now? @zachzwei <https://github.com/zachzwei> & @catenocrypt
<https://github.com/catenocrypt>,

**Pull request merged**
